# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BridgeDisplay.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BridgeDispMW(object):
    def setupUi(self, BridgeDispMW):
        BridgeDispMW.setObjectName(_fromUtf8("BridgeDispMW"))
        BridgeDispMW.resize(750, 600)
        BridgeDispMW.setMaximumSize(QtCore.QSize(900, 16777215))
        BridgeDispMW.setStyleSheet(_fromUtf8("backgroundcolor rgb(85, 170, 255)"))
        self.centralwidget = QtGui.QWidget(BridgeDispMW)
        self.centralwidget.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(15, 15, 375, 375))
        self.frame.setStyleSheet(_fromUtf8("background:rgb(0,0,0)"))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.ActualGB = QtGui.QGroupBox(self.centralwidget)
        self.ActualGB.setGeometry(QtCore.QRect(425, 315, 281, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ActualGB.setFont(font)
        self.ActualGB.setStyleSheet(_fromUtf8("background:rgb(0,0,0);color:rgb(0,200,0)"))
        self.ActualGB.setObjectName(_fromUtf8("ActualGB"))
        self.act_course_label = QtGui.QLabel(self.ActualGB)
        self.act_course_label.setGeometry(QtCore.QRect(0, 30, 101, 40))
        self.act_course_label.setStyleSheet(_fromUtf8("font: 20pt \"Ubuntu\";color rgb(0, 85, 0)"))
        self.act_course_label.setFrameShape(QtGui.QFrame.Box)
        self.act_course_label.setAlignment(QtCore.Qt.AlignCenter)
        self.act_course_label.setObjectName(_fromUtf8("act_course_label"))
        self.act_spd_label = QtGui.QLabel(self.ActualGB)
        self.act_spd_label.setGeometry(QtCore.QRect(190, 30, 91, 40))
        self.act_spd_label.setStyleSheet(_fromUtf8("font: 20pt \"Ubuntu\";color rgb(0, 85, 0)"))
        self.act_spd_label.setFrameShape(QtGui.QFrame.Box)
        self.act_spd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.act_spd_label.setObjectName(_fromUtf8("act_spd_label"))
        self.CmmdGB = QtGui.QGroupBox(self.centralwidget)
        self.CmmdGB.setGeometry(QtCore.QRect(425, 235, 281, 75))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.CmmdGB.setFont(font)
        self.CmmdGB.setStyleSheet(_fromUtf8("background:rgb(0,0,0);color:rgb(0,200,0)"))
        self.CmmdGB.setObjectName(_fromUtf8("CmmdGB"))
        self.cmd_spd_label = QtGui.QLabel(self.CmmdGB)
        self.cmd_spd_label.setGeometry(QtCore.QRect(190, 30, 91, 40))
        self.cmd_spd_label.setStyleSheet(_fromUtf8("font: 20pt \"Ubuntu\";color rgb(85, 0, 255)"))
        self.cmd_spd_label.setFrameShape(QtGui.QFrame.Box)
        self.cmd_spd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cmd_spd_label.setObjectName(_fromUtf8("cmd_spd_label"))
        self.cmd_course_label = QtGui.QLabel(self.CmmdGB)
        self.cmd_course_label.setGeometry(QtCore.QRect(0, 30, 101, 40))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.cmd_course_label.setFont(font)
        self.cmd_course_label.setStyleSheet(_fromUtf8("font: 63 20pt \"Ubuntu\";color rgb(85,0,255)"))
        self.cmd_course_label.setFrameShape(QtGui.QFrame.Box)
        self.cmd_course_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cmd_course_label.setObjectName(_fromUtf8("cmd_course_label"))
        self.Dist2GoalGB = QtGui.QGroupBox(self.centralwidget)
        self.Dist2GoalGB.setGeometry(QtCore.QRect(425, 20, 225, 110))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Dist2GoalGB.setFont(font)
        self.Dist2GoalGB.setStyleSheet(_fromUtf8("color:rgb(120,120,120)"))
        self.Dist2GoalGB.setObjectName(_fromUtf8("Dist2GoalGB"))
        self.dist_label = QtGui.QLabel(self.Dist2GoalGB)
        self.dist_label.setGeometry(QtCore.QRect(0, 40, 220, 55))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.dist_label.setFont(font)
        self.dist_label.setStyleSheet(_fromUtf8("color:rgb(120,120,120)"))
        self.dist_label.setFrameShape(QtGui.QFrame.Box)
        self.dist_label.setFrameShadow(QtGui.QFrame.Plain)
        self.dist_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dist_label.setObjectName(_fromUtf8("dist_label"))
        self.Time2GoalGB = QtGui.QGroupBox(self.centralwidget)
        self.Time2GoalGB.setGeometry(QtCore.QRect(425, 125, 225, 110))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Time2GoalGB.setFont(font)
        self.Time2GoalGB.setStyleSheet(_fromUtf8("color:rgb(120,120,120)"))
        self.Time2GoalGB.setObjectName(_fromUtf8("Time2GoalGB"))
        self.time_label = QtGui.QLabel(self.Time2GoalGB)
        self.time_label.setGeometry(QtCore.QRect(0, 40, 220, 55))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet(_fromUtf8("color:rgb(120,120,120)"))
        self.time_label.setFrameShape(QtGui.QFrame.Box)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        BridgeDispMW.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BridgeDispMW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        BridgeDispMW.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BridgeDispMW)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BridgeDispMW.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(BridgeDispMW)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        BridgeDispMW.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(BridgeDispMW)
        QtCore.QMetaObject.connectSlotsByName(BridgeDispMW)

    def retranslateUi(self, BridgeDispMW):
        BridgeDispMW.setWindowTitle(_translate("BridgeDispMW", "ROV Jason DP Bridge Monitor ", None))
        self.ActualGB.setTitle(_translate("BridgeDispMW", "Actual Course/Speed", None))
        self.act_course_label.setText(_translate("BridgeDispMW", "COG", None))
        self.act_spd_label.setText(_translate("BridgeDispMW", "SOG", None))
        self.CmmdGB.setTitle(_translate("BridgeDispMW", "Commanded Course/Speed", None))
        self.cmd_spd_label.setText(_translate("BridgeDispMW", "SOG", None))
        self.cmd_course_label.setText(_translate("BridgeDispMW", "COG", None))
        self.Dist2GoalGB.setTitle(_translate("BridgeDispMW", "Distance to Goal", None))
        self.dist_label.setText(_translate("BridgeDispMW", "Distance, m", None))
        self.Time2GoalGB.setTitle(_translate("BridgeDispMW", "Time to Goal", None))
        self.time_label.setText(_translate("BridgeDispMW", "Time, s", None))
        self.toolBar.setWindowTitle(_translate("BridgeDispMW", "toolBar", None))

